[project]
name = "prompt-server"
version = "0.1.0"
description = "An MCP server containing prompts for the SRE agent."
requires-python = ">=3.12, <4.0"
dependencies = [
    "fastapi>=0.115.12",
    "mcp[cli]>=1.6.0",
]
